# Generated by Django 5.2.4 on 2025-07-04 15:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title for the expense/income record.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description for the record.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The base amount of the transaction before tax.', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Income)'), ('debit', 'Debit (Expense)')], help_text="Type of transaction: 'credit' (income) or 'debit' (expense).", max_length=6)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The tax value. Interpreted as flat amount or percentage based on 'tax_type'.", max_digits=10)),
                ('tax_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percentage', 'Percentage')], default='flat', help_text="Type of tax calculation: 'flat' or 'percentage'.", max_length=10)),
                ('date', models.DateField(help_text='The date when the record was made (YYYY-MM-DD).')),
                ('tax_amount_calculated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The calculated tax amount based on 'amount', 'tax', and 'tax_type'.", max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total amount including tax (amount + tax_amount_calculated).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('user', models.ForeignKey(help_text='The user who recorded this expense/income.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
